name: push-release

on:
  push:
    branches:
      - master

jobs:
  build_test_publish:
    name: Build, test, and publish unstable release
    if: "contains(github.event.head_commit.message, 'chore(release): publish')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: git config user.name "Mattr CI"
      - run: git config user.email "npmjs_ci_mattr_public@mattr.global"
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLIC_TOKEN }}
      - run: yarn publish:release
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLIC_TOKEN }}
