name: push-release

on:
  push:
    tags:
      - "release"

jobs:
  build_test_publish:
    name: Build, test, and publish unstable release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # checkout master explicitly as workflow triggered on a tag which results in checkout of detached HEAD
          ref: master
          # 0 indicates all history, needed for correct unstable version generation (commit count since last release)
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: "https://registry.npmjs.org"

      - name: Install, lint and build
        run: |
          yarn install --frozen-lockfile
          yarn format
          yarn lint
          yarn build

      - name: Test (unit)
        run: yarn test

      - name: Publish unstable release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLIC_TOKEN }}
        run: |
          git config user.name "Mattr CI"
          git config user.email "npmjs_ci_mattr_public@mattr.global"
          npm whoami
          yarn publish:release
